- Effect: Allow
  Action:
    - dynamodb.GetItem
    - dynamodb.PutItem
    - s3:PutBucketPolicy
    - s3:GetEncryptionConfiguration
    - s3:PutEncryptionConfiguration
  Resource: "arn:aws:dynamodb:${self.provider.region}:*:table/${self:custom.tableName}"
  